baseURL = "https://tardfyou.github.io/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
title = "Vincent"
theme = "LoveIt"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
copyright = "Tardfyou"

[pagination]
  pagerSize = 10
  path = "page"

[permalinks]
  posts = "/posts/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "文章"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "标签"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "分类"
    url = "/categories/"

[params]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  title = "Vincent"
  description = "Vincent's Blog"
  images = ["/img/train1.png"]

  [params.author]
    name = "Tardfyou"
    email = "3143596095@qq.com"
    link = "https://github.com/Tardfyou"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "Vincent"
      typeit = false

  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2023
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    title = "Vincent"
    noFavicon = true
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = false
    type = "fuse"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/img/train1.png"
      title = "Vincent"
      subtitle = "What pains us trains us."
      typeit = false
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "Tardfyou"
    Email = "3143596095@qq.com"

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = true
    linkToMarkdown = false
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 100
    [params.page.math]
      enable = false
    [params.page.share]
      enable = false
    [params.page.comment]
      enable = false
